export enum EVENT {
  CYCLE_STARTED = "cycle started",
  CYCLE_COMPLETE = "cycle complete",
  CYCLE_CRASHED = "cycle crashed",
  TEMPERATURE_SETTING_CHANGED = "temperature settings changed",
  LIVESTOCK_ADDED = "livestock added",
  LIVESTOCK_REMOVED = "livestock removed",
  LIVESTOCK_DIED = "livestock died",
  PLANT_ADDED = "plant added",
  PLANT_REMOVED = "plant removed",
  PLANT_DIED = "plant died",
  LIGHT_SETTINGS_CHANGED = "light settings changed",
  PARAMETER_TESTED = "tested",
  TEST_SCHEDULE_CHANGED = "test schedule changed",
  AILMENT_DX = "ailment diagnosed",
  AILMENT_CURED = "ailment cured",
  WATER_CHANGE = "water change",
  WATER_COLUMN_FERTILIZED = "water column fertilized",
  SUBSTRATE_FERTILIZED = "substrate fertilized",
  ALGICIDE_ADDED = "algicide added",
  MEDICATION_ADDED = "medication added",
  BACTERIA_ADDED = "nitrifying bacteria added",
  BIOFILM_ADDED = "biofilm added",
  LIVESTOCK_FED = "livestock fed",
  PRODUCT_ADDED = "product added",
  NONE = ""
}